initialisation
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #1
Opened 2023-10-04 10:03 UTC by Mikazian

2023-10-04 12:15 UTC, YDrogen requested changes

2023-10-04 12:15 UTC, YDrogen commented on package.json
> +    "sass": "^1.68.0",
Pourquoi `sass` ?

2023-10-04 12:15 UTC, YDrogen commented on vite.config.prod.js
> +  base: '/gamepulse/', // TODO: use the right repo name
Pas bon, il faut que ce soit le nom de votre repo Github

2023-10-04 12:16 UTC, YDrogen requested changes
Attention, il faut bien choisir la branche `develop` en destination !

2023-10-04 12:58 UTC, Mikazian commented on package.json
> +    "sass": "^1.68.0",
Pour le cube

2023-10-04 14:16 UTC, YDrogen requested changes

2023-10-04 14:16 UTC, YDrogen commented on vite.config.prod.js
> +  base: '/023-09-orleans-cda-projet1-groupe-b/', // TODO: use the right repo name
Toujours pas, il manque un 2 au début

2023-10-05 07:18 UTC, YDrogen commented
Je dois être le dernier à valider la PR (demande à tes collègues avant) :D

2023-10-05 07:53 UTC, Cardamced approved these changes

2023-10-05 08:04 UTC, YDrogen approved these changes

2023-10-05 08:04 UTC, merged