fixe fetch methods
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #11
Opened 2023-10-16 11:58 UTC by Mikazian

2023-10-16 12:04 UTC, Cardamced approved these changes

2023-10-17 14:11 UTC, YDrogen requested changes

2023-10-17 14:11 UTC, YDrogen commented on src/components/home/HeaderHome.jsx
> +    };
Peuvent être sorties hors du component

2023-10-17 14:11 UTC, YDrogen commented on src/components/home/HeaderHome.jsx
> +  if (isLoaded) {
Plus lisible de faire l'inverse
```jsx
if (!isLoaded) {
  return null
}

// suite
```

2023-10-17 14:11 UTC, YDrogen commented on src/components/gameshow/Thumbnails.jsx
> +  if (isLoaded) {
idem

2023-10-17 14:11 UTC, YDrogen commented on src/api/api-fetch.js
> +  loading,
Plus parlant un `setLoaded` par exemple

2023-10-17 14:11 UTC, YDrogen commented on src/api/api-fetch.js
> +    loading(true), setter(data);
pardon ?
```js
loading(true);
setter(data);
```
C'est mieux non ? 👀

2023-10-17 14:11 UTC, YDrogen commented on src/api/api-fetch.js
> +  loading,
pareil partout

2023-10-17 14:49 UTC, herve-perel approved these changes

2023-10-18 07:21 UTC, YDrogen requested changes

2023-10-18 07:21 UTC, YDrogen commented on src/components/gameshow/Thumbnails.jsx
> +  } else {
L'avantage du `return` dans le `if` c'est que tu n'as pas besoin de `else` ça allège la PR du coup 😄

2023-10-18 07:21 UTC, YDrogen commented on src/components/home/HeaderHome.jsx
> +  } else {
idem

2023-10-18 08:54 UTC, Cardamced approved these changes

2023-10-18 09:31 UTC, YDrogen approved these changes

2023-10-18 09:31 UTC, merged