Feature/categories
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #12
Opened 2023-10-18 09:27 UTC by herve-perel

2023-10-18 09:59 UTC, Mikazian submitted a review, later dismissed

2023-10-18 13:41 UTC, ElBarto444 approved these changes

2023-10-20 09:30 UTC, Cardamced commented on src/components/genres/CarouselCard.jsx
Vu avec Hervé - Code commenté l-39 - 41 : en prévision de récupérer les données de la PR feature/game infos, pour boucler dessus.

2023-10-20 09:32 UTC, Cardamced commented on src/components/genres/HeaderGenre.jsx
Harmonisation : Commentaires après // ou commentaires entre {/* */} ?

2023-10-20 09:32 UTC, Cardamced approved these changes

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/CarouselCard.jsx
> +          <img
isLoaded n'est pas utilisé !
ajouter à ta balise <img> : 
```html

``` {isLoaded ? (<img>) : (<p>Loading...</p>)}

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/CarouselCard.jsx
> +                  <h5 className="clamp-title-card mt-3 font-title uppercase tracking-wide text-light">
pareil ici : 
```html

```  {isLoaded ? (<h5>...</h5>) : (<p>Loading...</p>)}

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/CarouselCard.jsx
> +                  <p className="metascore-size font-black">{game.metacritic}</p>
```html
{isLoaded ? (<p>...</p>) : (<p>Loading...</p>)}
```

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/CarouselCard.jsx
> +                {game.genres.map((genre) => (
```html
{isLoaded ? (game.genres.map((genre) => (
                  <div
                    key={genre.id}
                    className="text-white skew-x-[-35deg] rounded-[2px] bg-primary/50 px-4 py-1 text-xs"
                  >
                    <div className="skew-x-[35deg]">{genre.name}</div>
                  </div>
                ))) : (<p>Loading...</p>)}
```

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/CarouselCard.jsx
> +          </p>{' '}
attention retirer : {' '}

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/CarouselCard.jsx
> +          <p className="mt-5 font-text text-base text-light/80">
```html
{isLoaded ? (<p>...</p>) : (<p>Loading...</p>)}
```

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/CarouselCard.jsx
> +            <p className="mt-5 line-clamp-4 text-light/80">
```html
{isLoaded ? (<p>...</p>) : (<p>Loading...</p>)}
```

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/CarouselCard.jsx
> +          </div>{' '}
retirer { ' ' }

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/Categories.jsx
> +            Jeu {slug}
Jeu en anglais

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/HeaderGenre.jsx
> +          {/* Affichage de l'image si en dessous de 768px */}
Retirer ce commentaire, il ne sert pas à ce composant

2023-10-20 09:51 UTC, Mikazian commented on src/router.jsx
> +// import * as React from 'react';
Code commenté, à retirer

2023-10-20 09:51 UTC, Mikazian commented on src/router.jsx
> +        path: '/genre/:slug',
genre avec un "s"

2023-10-20 09:51 UTC, Mikazian commented on src/components/genres/Carousel.jsx
Ta des messages warning sur tes useCallback je ne connais pas cette fonction

2023-10-20 10:20 UTC, Mikazian approved these changes

2023-10-23 08:18 UTC, YDrogen requested changes

2023-10-23 08:18 UTC, YDrogen commented on src/App.css
> +  }
`size` ou `clamp` dans le nom de class ?
Soit
```css
.text-size {}
.title-size {}
```
soit
```css
.text-clamp {}
.title-clamp {}
```

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/CarouselCard.jsx
> +  }, [game.id]);
Il manque la fonction cleanup

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/Carousel.jsx
> +        <div className=" mx-auto mt-0 h-full w-full overflow-hidden xl:w-[52vw]">
espace en trop

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/Carousel.jsx
> +            className="h-full w-full transition-transform duration-500 ease-out lg:h-[45vw] xl:h-full xl:max-w-[52vw] "
espace en trop

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/Carousel.jsx
> +              ></div>
Peut être fermé directement

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/CarouselCard.jsx
> +        <div className="flex-col px-4 xl:w-full ">
espace en trop

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/CarouselCard.jsx
> +          <div className=" ">
className inutile

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/CarouselCard.jsx
> +                <div className="">
className inutile

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/CarouselCard.jsx
> +          </div>{' '}
espace inutile

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/CarouselCard.jsx
> +                      {' '}
espace inutile

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/CarouselCard.jsx
> +                      <div className="skew-x-[35deg]">{genre.name}</div>{' '}
espace inutile

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/Categories.jsx
> +  const currentGame = games?.results?.[gameIndex] || [];
`currentGame` n'est pas censé être une array

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/Categories.jsx
> +  }, [slug]);
Il manque la fonction cleanup

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/Categories.jsx
> +        <div className="ml-10 flex flex-col ">
espace en trop

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/GridCard.jsx
> +        <div className="my-20 ml-10 flex flex-col ">
espace en trop

2023-10-23 08:18 UTC, YDrogen commented on src/components/genres/GridCard.jsx
> +          <h1 className=" text-start font-title text-7xl text-light">
espace en trop

2023-10-23 08:18 UTC, YDrogen commented on package.json
> +    "react-responsive-carousel": "^3.2.23",
Jamais utilisé ?

2023-10-23 08:18 UTC, YDrogen commented on package.json
> +    "flowbite-react": "^0.6.4",
Idem ?

2023-10-24 09:18 UTC, Mikazian approved these changes

2023-10-24 15:06 UTC, YDrogen requested changes

2023-10-24 15:06 UTC, YDrogen commented on src/App.jsx
> +import Navbar from './components/Navbar';
Il était bien à la ligne 2
Ça évite de rajouter un changement à review

2023-10-24 15:06 UTC, YDrogen commented on src/components/genres/Carousel.jsx
> +  games = games?.results?.slice(0, 10);
Surtout pas, interdiction de réassigner des props.
Fais une nouvelle const à la place

2023-10-25 08:26 UTC, ElBarto444 approved these changes

2023-10-25 08:44 UTC, Cardamced approved these changes
Ok pour le code commenté qui prépare le map sur les platforms.

2023-10-25 09:20 UTC, YDrogen approved these changes

2023-10-25 09:20 UTC, merged