Feature/game infos
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #14
Opened 2023-10-18 12:45 UTC by ElBarto444

2023-10-18 13:41 UTC, herve-perel submitted a review, later dismissed

2023-10-19 09:47 UTC, YDrogen requested changes

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/DlcComponent.jsx
> +  } else {
Si tu `return` dans le `if` tu peux te passer de `else`; ça allège d'un niveau d'indentation

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/DlcComponent.jsx
> +                    src="/src/assets/dlc.png"
Chemin pas bon (voir autre commentaire)

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/MetascoreColor.jsx
Ne contient pas de `jsx` donc un `.js` suffit
\+ à changer de dossier vu que ce n'est pas un component
(+ impec la licence/auteur/source 👍 )

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +  const [retro, setRetro] = useState([]);
state pas utilisé

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +  const triggerEl = document.getElementById('tooltipButton');
Pas une bonne pratique d'utiliser la manipulation de dom en React. Autant l'éviter quand c'est possible.
Ici, tu peux utiliser les `ref` de React avec le hook [`useRef`](https://react.dev/reference/react/useRef)

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +  const tooltip = new Tooltip(targetEl, triggerEl, options);
Pas besoin de stocker dans une `const` si tu l'utilise pas ensuite
```suggestion
  new Tooltip(targetEl, triggerEl, options);
```
suffit

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +        <div className="rightbar w-25 container rounded-lg border border-primary bg-primary/10 p-4">
`rightbar` n'est pas utilisé / n'existe pas ?

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +              id="tooltipButton"
Les `id` ne sont plus nécessaires du coup avec les refs

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +            Editions and DLC&apos;s {game.name}
Quand il y a des caractères spéciaux, il faut encapsuler dans des `{""}`
```suggestion
            {`Editions and DLC's ${game.name}`}
```

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +            src="/src/assets/separator.png"
Attention lien pas bon

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +                  <button className="storeButton my-2 inline-flex w-full items-center justify-center rounded bg-[#0D4F61] text-center font-bold text-light transition duration-150 hover:-translate-y-0
`storeButton` ?

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +        <div className="rightbar w-25 container mt-5 rounded-lg border border-primary bg-primary/10 p-4">
`rightbar` ?

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +            src="/src/assets/separator.png"
attention lien

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +                      className="pfLogo m-auto mt-1 h-6"
`pfLogo` ?

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +        <div className="rightbar w-25 container mt-5 rounded-lg border border-primary bg-primary/10 p-4">
`rightbar` ?

2023-10-19 09:47 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +RightBar.jsx;
Que fait cette ligne ?

2023-10-19 12:43 UTC, Mikazian submitted a review, later dismissed

2023-10-20 09:42 UTC, YDrogen requested changes

2023-10-20 09:42 UTC, YDrogen commented on public/75882-tux-icons-linux-computer-ubuntu-logo.png
Pas utilisée ?

2023-10-20 09:42 UTC, YDrogen commented on public/gog-com-seeklogo.com-3.svg
Pas utilisée ?

2023-10-20 09:43 UTC, YDrogen commented
+ d'autres demandes plus haut pas résolues

2023-10-20 09:59 UTC, Mikazian commented on public/196px-PEGI_18.svg.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/197px-PEGI_12.svg.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/197px-PEGI_16.svg.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/197px-PEGI_3.svg.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/75882-tux-icons-linux-computer-ubuntu-logo.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/PEGI_7.svg.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/android.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/appstore.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/dlc.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/epic-games.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/gog-com-seeklogo.com-3.svg
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/gog.png
ajouter ces images dans un dossier public/images

2023-10-20 09:59 UTC, Mikazian commented on public/ios.png
ajouter ces images dans un dossier public/images

2023-10-23 08:19 UTC, YDrogen commented
D'autres demandes par résolues plus haut

2023-10-24 19:32 UTC, Mikazian commented
Tu as 10 conversations qui doivent être résolu
![Capture d’écran 2023-10-24 à 21 31 39](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b/assets/120253140/2d4b9af2-4434-489a-aba8-cf5bbcc47820)

2023-10-25 07:24 UTC, Cardamced approved these changes
Impeccable pour moi.

2023-10-25 07:38 UTC, YDrogen approved these changes

2023-10-25 07:39 UTC, merged