Feature/game desc and specs
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #15
Opened 2023-10-19 10:07 UTC by ElBarto444

2023-10-19 11:53 UTC, Cardamced submitted a review, later dismissed

2023-10-19 11:53 UTC, Mikazian submitted a review, later dismissed

2023-10-19 14:28 UTC, YDrogen requested changes

2023-10-20 09:53 UTC, Mikazian commented on src/App.jsx
> +      <main className="relative flex h-fit flex-row flex-nowrap">
enlever le h-fit, plus besoin de préciser la hauteur du conteneur main

2023-10-20 09:53 UTC, Mikazian commented on src/assets/block.png
retirer cette image, déjà générer en css

2023-10-20 09:53 UTC, Mikazian commented on src/components/Title.jsx
> +import { useRef } from 'react';
retirer ce hook, on a modifié le code

2023-10-20 09:53 UTC, Mikazian commented on src/components/gameshow/ReadMore.jsx
> +import React, { useState } from 'react';
enlever React, laisser le hook

2023-10-23 08:23 UTC, YDrogen requested changes

2023-10-23 08:23 UTC, YDrogen commented on src/components/gameshow/ReadMore.jsx
> +  const text = children;
Pas une bonne idée ça
Tu peux envoyer le text en props, ça sera plus safe
Techniquement le children pourrait être autre chose que du texte (et ça casserait tout)

2023-10-23 08:23 UTC, YDrogen commented on src/components/gameshow/TextFormatter.jsx
Ce genre de fichiers utilitaires peut être déplacé dans un dossier `utils` (`/src/utils`)

2023-10-24 19:23 UTC, Mikazian submitted a review, later dismissed

2023-10-24 19:38 UTC, Mikazian approved these changes

2023-10-25 07:44 UTC, YDrogen submitted a review, later dismissed

2023-10-26 12:31 UTC, herve-perel approved these changes

2023-10-26 14:09 UTC, YDrogen approved these changes

2023-10-26 14:09 UTC, merged