Feature/retro
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #16
Opened 2023-10-19 10:28 UTC by Cardamced

2023-10-19 10:33 UTC, ElBarto444 submitted a review, later dismissed

2023-10-19 12:35 UTC, Mikazian approved these changes

2023-10-19 13:32 UTC, herve-perel approved these changes

2023-10-19 13:58 UTC, Mikazian approved these changes

2023-10-23 08:26 UTC, YDrogen commented on src/components/Retro/RetroContainer.jsx
> +            <a className=" rotate-360 p-2 hover:bg-light hover:text-dark">{`Enter >`}</a>
espace en trop

2023-10-23 08:27 UTC, YDrogen commented on src/components/Retro/Cube3D.jsx
> +              <source src="/images/Sonic.mp4" type="video/mp4" />
Pourquoi 2 sources ?

2023-10-23 08:27 UTC, YDrogen commented on src/components/Retro/Cube3D.jsx
> +              <source src="/images/Sonic.mp4" type="video/mp4" />
`.mp4` c'est pas une image 🤔

2023-10-23 08:28 UTC, YDrogen commented on tailwind.config.js
> +  plugins: [require('flowbite/plugin')],
Pas utilisé ?

2023-10-23 08:28 UTC, YDrogen commented on tailwind.config.js
> +
saut de ligne inutile

2023-10-23 08:28 UTC, YDrogen commented on tailwind.config.js
> +
saut de ligne inutile

2023-10-23 08:30 UTC, YDrogen commented on src/components/Navbar.jsx
> +          <li className=" gap-3 font-bold text-light">
espace en trop

2023-10-23 08:30 UTC, YDrogen commented on src/components/Navbar.jsx
> +          <li className=" mb-5 gap-3 font-bold text-light">
espace en trop

2023-10-23 08:30 UTC, YDrogen commented on src/components/Navbar.jsx
> +import '../App.jsx';
Pourquoi cet import ?

2023-10-23 08:31 UTC, YDrogen commented on src/components/Navbar.jsx
> +import React, { useState } from 'react';
![image](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b/assets/13053644/bb82575b-5a8b-4494-ac35-2a51f35e62c8)

2023-10-23 08:32 UTC, YDrogen commented on src/App.jsx
> +        )}
Moyen sûr de ça
Mieux vaut laisser ça pour une autre PR

2023-10-23 08:33 UTC, YDrogen commented on src/App.css
> +}
A bouger dans `tailwind.config`

2023-10-23 08:35 UTC, YDrogen commented on src/App.css
> +  }
1. Faire une class `.preserve-3d`
2. Déplacer l'animation dans `tailwind.config`
3. Faire une class `.pause-animation` et l'utiliser [comme d'habitude](https://tailwindcss.com/docs/hover-focus-and-other-states#hover-focus-and-active)

2023-10-23 08:36 UTC, YDrogen commented on src/App.css
> +}
Devrait se trouver dans le [`@layer components`](https://tailwindcss.com/docs/adding-custom-styles#adding-component-classes)
+ avec des noms plus parlants `.cube-front` `.cube-back` ...

2023-10-23 08:37 UTC, YDrogen commented on src/App.css
> +    transform: rotateY(25deg);
Tu peux renommer celle-ci en `.perspective-700` par exemple

2023-10-23 08:38 UTC, YDrogen commented on src/App.css
> +}
puis celle-ci en `.perspective-(nb de px)` en remplaçant `40rem` en px
+ la déplacer dans la layer au dessus

2023-10-23 08:38 UTC, YDrogen commented on src/App.css
> +  mask-repeat: no-repeat;
À placer dans la layer

2023-10-24 22:46 UTC, Cardamced commented on package.json
> +    "flowbite-react": "^0.6.4",
Pas à ma connaissance, c'est un vestige d'un test. Mais apparemment, on ne peut plus s'en passer, ça fait péter le code.

2023-10-24 23:06 UTC, Cardamced commented on src/components/NavbarTools/FilteredPlatforms.jsx
A rien, c'était un fichier pour déporter le filtrage qu'on fait finalement ailleurs. Il doit être supprimé.

2023-10-24 23:11 UTC, Cardamced commented on src/App.jsx
> +    });
Excellente question réglée désormais par le fetch directement dans la navbar. Se pose quand même la question du maintien du fetchGamesElements dans le RetroContainer... enfin bon, ça ne concerne plus ce fichier.

2023-10-24 23:12 UTC, Cardamced commented on src/components/Retro/Cube3D.jsx
> +              <source src="/images/Sonic.mp4" type="video/mp4" />
J'avais trouvé une ressource sur le net qui montrait qu'au cas où la première n'était pas trouvée/disponible, la seconde prenait le relai.

2023-10-24 23:13 UTC, Cardamced commented on src/components/Retro/Cube3D.jsx
> +              <source src="/images/Sonic.mp4" type="video/mp4" />
C'est une vidéo dans le dossier images. J'ai tout retiré et ne remettrai qu'en guise de placeholder si besoin et au compte-goutte. Dans un fix.

2023-10-24 23:14 UTC, Cardamced commented on tailwind.config.js
> +  plugins: [require('flowbite/plugin')],
Si je le retire, ça pète tout.

2023-10-24 23:14 UTC, Cardamced commented on tailwind.config.js
> +
Done

2023-10-24 23:15 UTC, Cardamced commented on tailwind.config.js
> +
Done

2023-10-24 23:15 UTC, Cardamced commented on src/components/Navbar.jsx
> +          <li className=" gap-3 font-bold text-light">
Done

2023-10-24 23:15 UTC, Cardamced commented on src/components/Navbar.jsx
> +          <li className=" mb-5 gap-3 font-bold text-light">
:'-|

2023-10-24 23:17 UTC, Cardamced commented on src/components/Navbar.jsx
> +import '../App.jsx';
C'est ôté.

2023-10-24 23:19 UTC, Cardamced commented on src/App.jsx
> +        )}
C'est ôté.

2023-10-25 09:35 UTC, Cardamced commented on src/components/Title.jsx
> +  const isInView = useInView(ref, { once: true });
Done.

2023-10-25 09:36 UTC, Cardamced commented on src/components/Retro/RetroContainer.jsx
> +import React from 'react';
Sauf erreur, le fetchGameElements est utilisé pour aller (à terme) chercher les ressources de l'API pour illustrer les faces du cube.

2023-10-25 09:36 UTC, Cardamced commented on src/components/News.jsx
Indeed...

2023-10-25 09:42 UTC, Cardamced commented on package.json
> +    "react-intersection-observer": "^9.5.2",
C'est enlevé.

2023-10-25 09:44 UTC, Cardamced commented on src/components/NavbarTools/Dropdown.jsx
> +  }, [isOpen]);
C'est corrigé ailleurs. Je ne push pas ce fichier.

2023-10-25 09:46 UTC, Cardamced commented on src/components/Home.jsx
> +          ))} */}
Done. Du reste ce fichier home est outdated. Il sera supprimé.

2023-10-25 11:42 UTC, Cardamced commented on src/App.css
> +}
Done.

2023-10-25 12:09 UTC, Cardamced commented on src/App.css
> +}
Ok.

2023-10-25 12:14 UTC, Cardamced commented on src/App.css
> +  mask-repeat: no-repeat;
Done.

2023-10-25 13:33 UTC, ElBarto444 submitted a review, later dismissed

2023-10-26 08:24 UTC, herve-perel approved these changes

2023-10-26 13:01 UTC, YDrogen requested changes

2023-10-27 11:48 UTC, Mikazian approved these changes

2023-10-27 11:53 UTC, YDrogen requested changes

2023-10-27 11:53 UTC, YDrogen commented on src/App.jsx
Pourquoi retirer la navbar ?

2023-10-27 13:13 UTC, ElBarto444 approved these changes
OUI

2023-10-27 13:15 UTC, YDrogen approved these changes

2023-10-27 13:15 UTC, merged