Feature/home the unavoidable
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #17
Opened 2023-10-20 08:42 UTC by Mikazian

2023-10-20 08:48 UTC, Cardamced commented on src/components/Title.jsx
Title à reprendre avec celui complété de la branche feature/retro. Il y a une animation supplémentaire. Code à reprendre pour ne pas faire de conflits.

2023-10-20 08:52 UTC, Cardamced submitted a review, later dismissed
Bonne pratique des commentaires explicatifs pour séparer et bien identifier le rôle du code qui suit.
Je note le code du composant Title à surveiller, rapport à ma branche feature/retro.

2023-10-23 09:10 UTC, YDrogen requested changes
Nom de branche

2023-10-23 09:10 UTC, YDrogen commented on src/components/home/Unavoidable.jsx
> +  const TransformX = (val) =>
Pourquoi une maj ?

2023-10-23 09:10 UTC, YDrogen commented on src/components/home/Unavoidable.jsx
> +                    key={currentGame.background_image}
Pas besoin, les `key` sont seulement utiles pour les `.map`

2023-10-23 09:29 UTC, Mikazian commented on src/components/home/Unavoidable.jsx
> +  const TransformX = (val) =>
ES_Lint qui me m'oblige à l'écrire comme ça, de base il était en minuscule

2023-10-23 09:35 UTC, closed without merging

2023-10-23 09:35 UTC, Mikazian commented
change name branch