Feature/footer
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #18
Opened 2023-10-20 12:54 UTC by herve-perel

2023-10-20 12:56 UTC, ElBarto444 submitted a review, later dismissed

2023-10-20 12:56 UTC, ElBarto444 commented on src/components/Footer.jsx
Super

2023-10-20 12:57 UTC, Mikazian submitted a review, later dismissed

2023-10-23 09:11 UTC, YDrogen requested changes

2023-10-23 09:11 UTC, YDrogen commented on src/App.jsx
>        </footer>
Pourquoi ne pas mettre `<footer>` dans le component `Footer` ?

2023-10-24 09:12 UTC, Mikazian commented on src/App.jsx
Super tu as bien créé un composant et importé dans le fichier App

2023-10-24 09:12 UTC, Mikazian commented on src/components/Footer.jsx
Bon pratique l'utilisation de la balise sémantique footer

2023-10-24 09:12 UTC, Mikazian approved these changes

2023-10-24 15:07 UTC, YDrogen approved these changes

2023-10-24 15:07 UTC, merged