create new games carousel
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #22
Opened 2023-10-23 15:14 UTC by Mikazian

2023-10-23 15:19 UTC, ElBarto444 submitted a review, later dismissed
C'est bon pour moi

2023-10-23 15:19 UTC, Cardamced submitted a review, later dismissed
RAS. Je ne vois rien à redire.

2023-10-24 15:14 UTC, YDrogen requested changes

2023-10-24 15:14 UTC, YDrogen commented on src/components/home/PlatformsList.jsx
> +          ))
Petit tip, tu peux déconstruire ici
```suggestion
          game.parent_platforms.map(({ platform }, platformIndex) => (
            <li key={platformIndex}>{platformsLogos(platform)}</li>
          ))
```

2023-10-24 15:14 UTC, YDrogen commented on src/components/home/platformsLogos.jsx
Pourquoi pas de majuscule ? C'est une component qui retourne du JSX

2023-10-24 15:14 UTC, YDrogen commented on src/components/home/platformsLogos.jsx
> +};
il manque un return si on rentre dans aucun des `if`s

2023-10-24 22:21 UTC, Cardamced commented on src/components/home/CarouselHome.jsx
Attention, ligne 34, code commenté.

2023-10-24 22:24 UTC, Cardamced submitted a review, later dismissed
Juste enlever le code commenté s'il n'est pas nécessaire. RAS sinon.

2023-10-25 09:09 UTC, herve-perel submitted a review, later dismissed

2023-10-25 09:23 UTC, YDrogen requested changes

2023-10-25 09:23 UTC, YDrogen commented on src/components/home/platformsLogos.jsx
> +export const PlatformsLogos = (platformData) => {
Du coup c'est un component en fait
`platformData` devrait plutôt s'appeler `props` ou déconstruit

2023-10-25 09:23 UTC, YDrogen commented on src/components/home/platformsLogos.jsx
Il manque une maj dans le nom de fichier

2023-10-25 09:23 UTC, YDrogen commented on src/components/home/PlatformsList.jsx
> +            <li key={platformIndex}>{PlatformsLogos(platform)}</li>
Du coup ça s'appelle comme un component, avec des props

2023-10-26 07:37 UTC, Mikazian commented on src/components/home/PlatformsList.jsx
> +            <li key={platformIndex}>{PlatformsLogos(platform)}</li>
done

2023-10-26 07:37 UTC, Mikazian commented on src/components/home/platformsLogos.jsx
> +export const PlatformsLogos = (platformData) => {
done

2023-10-26 07:56 UTC, herve-perel submitted a review, later dismissed

2023-10-26 07:57 UTC, Cardamced approved these changes
Top !

2023-10-27 12:29 UTC, YDrogen requested changes
(+) commentaires précédents

2023-10-27 12:29 UTC, YDrogen commented on src/components/home/PlatformList.jsx
Je regarde

2023-10-27 12:29 UTC, YDrogen commented on src/components/home/PlatformsList.jsx
quel fichier ?

2023-10-28 15:51 UTC, closed without merging