Feature/scroll top
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #23
Opened 2023-10-24 15:26 UTC by herve-perel

2023-10-24 18:11 UTC, Cardamced commented on src/components/ScrollTop.jsx
Il y a du code commenté ici. Le useEffect n'est plus d'actualité ?

2023-10-25 08:41 UTC, Cardamced approved these changes
RAS.

2023-10-25 09:21 UTC, Mikazian commented on src/App.jsx
Création et importation du composant ScrollTop au top !

2023-10-25 09:21 UTC, Mikazian commented on src/components/ScrollTop.jsx
propre

2023-10-25 09:22 UTC, Mikazian approved these changes

2023-10-25 09:23 UTC, YDrogen requested changes
Mauvais nom de branche (voir readme)

2023-10-25 09:45 UTC, closed without merging