carousel best game
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #26
Opened 2023-10-26 07:53 UTC by herve-perel

2023-10-26 09:30 UTC, Mikazian approved these changes

2023-10-26 09:31 UTC, Cardamced submitted a review, later dismissed
Ok pour la PR déjà passée au préalable moyennant l'observation du tableau de dépendances.

2023-10-27 12:45 UTC, YDrogen requested changes

2023-10-27 12:45 UTC, YDrogen commented on src/components/genres/Carousel.jsx
> +    .sort((a, b) => b.metacritic - a.metacritic);
Tu peux chainer sur la première const
`games?.results?.slice(0, 10).sort((a,b) => // ...`

2023-10-27 12:58 UTC, Cardamced approved these changes
RAS.

2023-10-27 13:16 UTC, YDrogen approved these changes

2023-10-27 13:16 UTC, merged