Feature/redirection genre page
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #31
Opened 2023-10-27 13:16 UTC by herve-perel

2023-10-27 13:19 UTC, ElBarto444 submitted a review, later dismissed
Je valide

2023-10-29 18:37 UTC, YDrogen requested changes
T'as review les 103 fichiers @ElBarto444 ?

2023-10-30 09:47 UTC, Mikazian commented on src/components/Navbar.jsx
>                  {genres.map((genre, index) => (
isLoaded est définit mais pas utilisé, le mettre ici :
`{isLoaded ? (<Collapsible>...</Collapsible>) : (<p>Loading...</p>)}`

2023-10-31 09:39 UTC, Mikazian approved these changes

2023-10-31 09:40 UTC, Mikazian commented
Correction de mon commentaire check

2023-10-31 10:42 UTC, YDrogen approved these changes

2023-10-31 10:42 UTC, merged