Feature/search
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #34
Opened 2023-10-28 15:34 UTC by Mikazian

2023-10-30 08:36 UTC, Cardamced submitted a review, later dismissed
Pas de commentaire, tout me paraît très bien.

2023-10-30 10:43 UTC, herve-perel approved these changes

2023-10-31 10:41 UTC, YDrogen requested changes

2023-10-31 10:41 UTC, YDrogen commented on src/components/search/Search.jsx
> +          clearTimeout(timer);
Devrait se trouver dans le return du `useEffect`

2023-10-31 10:41 UTC, YDrogen commented on src/components/search/Search.jsx
> +          ></motion.div>
Tu peux fermer la div directement

2023-10-31 10:41 UTC, YDrogen commented on src/components/search/SearchBar.jsx
> +      ></motion.div>
idem

2023-10-31 10:41 UTC, YDrogen commented on src/components/search/useGameSearch.js
> +      setGames((prevGames) => [...new Set([...prevGames, ...allGames])]);
Pas besoin de spread dans une array vide si il n'y a qu'un seul spread
```suggestion
      setGames((prevGames) => new Set([...prevGames, ...allGames]));
```

2023-10-31 15:36 UTC, closed without merging