Feature/achievements reworked
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #37
Opened 2023-10-30 09:37 UTC by ElBarto444

2023-10-30 10:02 UTC, Mikazian commented
à part la div avec le className vide j'ai pas trop chose à redire

2023-10-30 13:01 UTC, Mikazian submitted a review, later dismissed

2023-10-31 10:55 UTC, YDrogen requested changes

2023-10-31 10:55 UTC, YDrogen commented on src/components/gameshow/Achievements.jsx
> +  const [show, setShow] = useState(Array(trophyNb.length).fill(false));
Pourquoi faire une nouvelle const ?
Pourquoi pas directement `useState(Array(10).fill(false)` ?

2023-10-31 10:55 UTC, YDrogen commented on src/components/gameshow/AchievementTooltip.jsx
> +  const [isPresent, safeToRemove] = usePresence();
Le `AnimatePresence` permet de te passer du `usePresence`

2023-10-31 10:55 UTC, YDrogen commented on src/components/gameshow/AchievementTooltip.jsx
> +      exit={isPresent ? { opacity: 1 } : safeToRemove} // Animate when the component is removed
Tu peux faire comme `initial` ou `animate` sans ternaire

2023-11-01 15:02 UTC, Mikazian submitted a review, later dismissed

2023-11-01 15:02 UTC, Mikazian commented
Résolution des conflicts check

2023-11-02 08:14 UTC, YDrogen requested changes

2023-11-02 08:14 UTC, YDrogen commented on src/components/gameshow/Achievements.jsx
> +                          key={Math.random(index)}
Surtout pas, l'idée des `key` c'est que la valeur soit stable d'un render à l'autre
Ici avec le `Math.random` cette valeur change à chaque render
Si tu as besoin de cette `key`, tu peux utiliser `trophy.id` comme au dessus

2023-11-02 09:47 UTC, YDrogen submitted a review, later dismissed

2023-11-02 10:20 UTC, herve-perel approved these changes

2023-11-02 10:22 UTC, Mikazian approved these changes

2023-11-02 10:30 UTC, YDrogen approved these changes

2023-11-02 10:30 UTC, merged