add picture to gameshow
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #41
Opened 2023-10-30 10:34 UTC by Mikazian

2023-10-30 13:03 UTC, herve-perel submitted a review, later dismissed

2023-10-30 13:04 UTC, Cardamced approved these changes
Très bien.

2023-10-31 16:18 UTC, YDrogen requested changes

2023-10-31 16:18 UTC, YDrogen commented on src/components/gameshow/GameShow.jsx
> +              {game.name && game.name}
Ah
Mauvaise idée ça, mieux vaut une ternaire

2023-11-01 14:52 UTC, Mikazian commented on src/components/gameshow/GameShow.jsx
> +              {game.name && game.name}
done

2023-11-01 18:46 UTC, Cardamced approved these changes
RAS.

2023-11-02 08:51 UTC, herve-perel approved these changes

2023-11-02 09:48 UTC, YDrogen approved these changes

2023-11-02 09:50 UTC, merged