create about the team page
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #43
Opened 2023-10-30 15:33 UTC by Mikazian

2023-10-31 09:02 UTC, herve-perel submitted a review, later dismissed
rien a redire

2023-10-31 11:00 UTC, YDrogen requested changes

2023-10-31 11:00 UTC, YDrogen commented on src/App.css
> +  }
Tailwind c'est bien sinon 👀 
```jsx
h-[calc(100vh - 3.5rem)]
```

2023-10-31 11:00 UTC, YDrogen commented on src/components/AboutTheTeam.jsx
> +       */}
commentaire pas utile

2023-10-31 12:37 UTC, Mikazian commented on src/App.css
> +  }
ça marche po

2023-10-31 12:38 UTC, Mikazian commented on src/components/AboutTheTeam.jsx
> +       */}
done

2023-10-31 15:51 UTC, herve-perel approved these changes

2023-10-31 16:20 UTC, YDrogen requested changes

2023-10-31 16:20 UTC, YDrogen commented on src/components/Footer.jsx
> +          <p className="me-10 text-light/70">GamePlus ® Legal Notices</p>
GamePlus

2023-11-01 14:33 UTC, Mikazian commented on src/components/Footer.jsx
> +          <p className="me-10 text-light/70">GamePlus ® Legal Notices</p>
done

2023-11-01 18:42 UTC, Cardamced commented on src/components/AboutTheTeam.jsx
Juste une observation, tu laisses le texte du alt="" vide ?

2023-11-01 18:45 UTC, Cardamced reviewed
Commentaire à propos des alt="" laissés vides... A terme, c'est apparemment important pour les audits SEO.

2023-11-02 08:12 UTC, Mikazian commented on src/components/AboutTheTeam.jsx
done

2023-11-02 08:50 UTC, herve-perel approved these changes

2023-11-02 09:51 UTC, YDrogen approved these changes

2023-11-02 09:52 UTC, merged