Feature/404 page
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #44
Opened 2023-10-30 15:57 UTC by ElBarto444

2023-10-31 09:02 UTC, herve-perel submitted a review, later dismissed
rien a redire

2023-10-31 11:02 UTC, YDrogen requested changes

2023-10-31 11:02 UTC, YDrogen commented on src/App.css
> +  }
Voir l'autre PR où ça a été fait

2023-10-31 11:02 UTC, YDrogen commented on src/router.jsx
> +      },
Si vous voulez que le lien comporte 404, le plus propre serait `/404` (sans `error`)
Sinon si vous voulez que `/vhruiezfnziue` affiche la page 404 sans redirection vous pouvez directement utiliser `<Error404 />` dans l'element du path `*`
Au choix

2023-10-31 15:06 UTC, herve-perel approved these changes

2023-10-31 15:07 UTC, herve-perel submitted a review, later dismissed

2023-10-31 15:23 UTC, YDrogen commented on src/App.css
> +  }
C'est un soucis d'espaces, il n'en faut pas, Tailwind aime pas ça

2023-10-31 15:57 UTC, Mikazian commented on src/App.css
> +  }
je l'ai fais de mon côté ça fonctionne, du coup supprimé la casse dans App.css et dans ta balise html :
`h-[calc(100vh-3.5rem)]`
sans espace

2023-10-31 16:05 UTC, ElBarto444 commented on src/App.css
> +  }
Muchas gracias ça marche, vous êtes bien trop aimables.

2023-11-01 15:02 UTC, Mikazian approved these changes

2023-11-02 08:15 UTC, YDrogen approved these changes

2023-11-02 08:15 UTC, merged