Ajout RatingComments & fix GameShow & RatingBox
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #48
Opened 2023-10-31 13:42 UTC by Cardamced

2023-10-31 13:45 UTC, ElBarto444 reviewed
Ça m'a l'air bon.

2023-10-31 15:01 UTC, herve-perel submitted a review, later dismissed
du code de qualité

2023-10-31 15:42 UTC, YDrogen requested changes

2023-10-31 15:42 UTC, YDrogen commented on src/components/gameshow/GameShow.jsx
> +              <RatingComments game={game} vote={vote} setVote={setVote} />
Pas besoin de la prop `vote` du coup (pas utilisée)

2023-10-31 15:42 UTC, YDrogen commented on src/components/gameshow/RatingComments.jsx
> +    setErrorComment(null);
Déjà dans les `else` au dessus
Soit tu enlèves les `else` soit tu enlève ces 3 lignes; au choix

2023-11-02 08:25 UTC, herve-perel approved these changes

2023-11-02 09:54 UTC, YDrogen approved these changes

2023-11-02 09:54 UTC, merged