Feature/search games
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #50
Opened 2023-10-31 15:35 UTC by Mikazian

2023-10-31 15:48 UTC, herve-perel approved these changes
tout me semble bon

2023-10-31 16:27 UTC, YDrogen requested changes

2023-10-31 16:27 UTC, YDrogen commented on src/components/search/CardGame.jsx
> +                src="/public/images/placeholder.webp"
Pas de public

2023-11-01 18:49 UTC, Cardamced commented on src/components/home/PlatformsLogo.jsx
Si on veut être tatillon, y'a un E à la fin de Commodore. ;-)

2023-11-01 18:53 UTC, Cardamced commented on src/components/search/SearchBar.jsx
Si tu utilises un hook custom, je ne sais pas ce que dira Sylvain, mais il doit être possible de le déporter dans le dossier hooks. J'y ai déjà mis le mien, useMenuAnimation. Peut-être une façon d'optimiser. En tout cas beau taf. Chapeau.

2023-11-01 18:55 UTC, Cardamced reviewed
Juste quelques observations. Mais RAS sinon. J'attends juste pour review.

2023-11-02 08:39 UTC, Mikazian commented on src/components/search/SearchBar.jsx
done

2023-11-02 08:48 UTC, herve-perel approved these changes

2023-11-02 09:59 UTC, herve-perel approved these changes

2023-11-02 12:58 UTC, merged