Release/v0.1.0
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #54
Opened 2023-11-02 15:21 UTC by herve-perel

2023-11-02 16:24 UTC, Mikazian commented
enlever la route et le composant BestSeller,
enlever toute la partie recommandation,
enlever les composants Offers, recommandations et bestSeller,
mettre le composant Title dans Categories.jsx,
dans headerGameShow dans la balise image, ajoute l'alt,
gameshow/PlatformLogo.jsx a retirer si n'est pas utilisé,
changer Categories en Genres,
carrousel en premier plan sur la gameshow,
fixe Cédrick dans about the team,
problème avec la police ARCADE,
filtre du Categories disparut ???
mettre une majuscule sur le nom des genres,
Carrousel du Categories qui passe par dessus la searchBar,
les cards au premier plan,
Dans le carrousel de Categories, utiliser le composant Button,
Searchbar modifier son zindex,
Ajouter du margin dans Gameshow, la rightbar et les informations,
Mettre en anglais la page gameshow,
Les logos des stores déformés,
Problème de key dans gameshow,
apparement y'a une <div> dans un <p> dans gamshow,
avatar dans about the team,
show more de unavoidable ne renvoie pas au haut de la page,

2023-11-02 16:25 UTC, Mikazian submitted a review, later dismissed

2023-11-02 16:26 UTC, Cardamced submitted a review, later dismissed
OK, compte-tenu des fix à effectuer.

2023-11-02 16:27 UTC, ElBarto444 submitted a review, later dismissed
C'est validé pour moi

2023-11-03 08:12 UTC, ElBarto444 approved these changes
C'est bon pour moi

2023-11-03 10:36 UTC, ElBarto444 submitted a review, later dismissed
C'est bon pour moi

2023-11-03 10:51 UTC, Mikazian approved these changes

2023-11-03 10:51 UTC, ElBarto444 approved these changes
Je valide la release

2023-11-03 10:51 UTC, Cardamced submitted a review, later dismissed
OK après examen le plus attentif possible.

2023-11-03 10:56 UTC, YDrogen requested changes
nommage des fichiers dans `public`
- minuscule
- kebab-case
- quand il y a des chiffres: `home-1.png` par exemple

2023-11-03 10:56 UTC, YDrogen commented on src/utils/MetascoreColor.js
Pourquoi majuscules dans le nom de fichier ? Ce n'est pas un component

2023-11-03 11:22 UTC, YDrogen requested changes

2023-11-03 11:22 UTC, YDrogen commented on src/components/home/Unavoidable.jsx
> +  const TransformX = (val) =>
Pourquoi une majuscule ?

2023-11-03 11:23 UTC, Mikazian commented on src/components/home/Unavoidable.jsx
> +  const TransformX = (val) =>
on avait deja vu ensemble, c'est ESlint qui me dit de l'écrire comme ça

2023-11-03 11:28 UTC, Mikazian commented on src/App.css
fait, changer App.css en main.css, importé dans main.jsx et importé dans App.jsx

2023-11-03 11:29 UTC, Mikazian submitted a review, later dismissed

2023-11-03 11:29 UTC, Cardamced submitted a review, later dismissed
RAS.

2023-11-03 11:30 UTC, ElBarto444 approved these changes
J'approuve

2023-11-03 13:17 UTC, YDrogen requested changes

2023-11-03 13:17 UTC, YDrogen commented on src/App.jsx
> +import './main.css';
Du coup doit être importé dans `main.jsx` et non ici

2023-11-03 13:17 UTC, YDrogen commented on src/components/gameshow/RightBar.jsx
> +                    <Link to={st.url}>
Les liens marchent pas ?

2023-11-03 13:18 UTC, YDrogen commented on src/components/home/Unavoidable.jsx
> +  const TransformX = (val) =>
Pourquoi ?

2023-11-03 13:36 UTC, Mikazian commented on src/App.jsx
> +import './main.css';
fait

2023-11-03 13:36 UTC, Mikazian commented on src/components/home/Unavoidable.jsx
> +  const TransformX = (val) =>
done

2023-11-03 13:43 UTC, Mikazian commented on src/components/gameshow/RightBar.jsx
> +                    <Link to={st.url}>
c'est corrigé

2023-11-03 13:45 UTC, Cardamced submitted a review, later dismissed
Top !

2023-11-03 13:48 UTC, Cardamced approved these changes

2023-11-03 13:48 UTC, ElBarto444 approved these changes

2023-11-03 13:48 UTC, Mikazian approved these changes

2023-11-03 13:55 UTC, YDrogen approved these changes

2023-11-03 13:55 UTC, merged