Feature/gameshow carousel
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #6
Opened 2023-10-09 08:36 UTC by Mikazian

2023-10-09 08:43 UTC, herve-perel approved these changes

2023-10-09 12:04 UTC, YDrogen requested changes

2023-10-09 12:04 UTC, YDrogen commented on src/components/gameshow/Thumbnail.jsx
> +export default function Thumbnail({ images, curr, handleThumbnailClick }) {
Attention à bien nommer les components. Ici c'est `Thumbnail` au singulier mais il render toutes les thumbnails

2023-10-09 14:00 UTC, Mikazian commented on src/style/fonts.css
> +  src: url('/public/fonts/GalakPro-Bold.otf');
done

2023-10-09 14:06 UTC, Mikazian commented on src/templates/gameshow/GameShow.jsx
> +import React, { useState, useEffect } from 'react';
done

2023-10-09 14:10 UTC, Mikazian commented on src/components/gameshow/ChevronLeft.jsx
done

2023-10-10 10:14 UTC, Cardamced approved these changes

2023-10-10 15:17 UTC, YDrogen requested changes

2023-10-10 15:17 UTC, YDrogen commented on src/App.jsx
> +          <Outlet></Outlet>
```suggestion
          <Outlet />
```

2023-10-10 15:17 UTC, YDrogen commented on src/components/gameshow/ThumbnailsPaginations.jsx
> +  console.log(typeof nbPages, nbPages);
Pas utile les 2 lignes

2023-10-10 15:17 UTC, YDrogen commented on src/api/api-fetch.js
> +  console.log('Signal:', signal);
`console.log` oublié

2023-10-10 15:17 UTC, YDrogen commented on src/api/api-fetch.js
Il manque le signal sur les autres fonctions

2023-10-10 15:17 UTC, YDrogen commented on src/components/gameshow/CarouselGameShow.jsx
> +export default function CarrouselGameShow({ images }) {
un seul `R` à Carousel

2023-10-10 15:17 UTC, YDrogen commented on src/components/gameshow/GameShow.jsx
> +    fetchGameDetails(gameId, setGameName, 'name', signal);
en mode objet aussi, histoire d'uniformiser tout ça

2023-10-10 15:17 UTC, YDrogen commented on src/components/gameshow/Thumbnails.jsx
> +  useEffect(() => {});
Ne sert pas

2023-10-10 15:17 UTC, YDrogen commented on src/components/gameshow/Thumbnails.jsx
> +  const numberImages = 5;
Les `const` qui ne changent pas comme celle ci peuvent être sorties des components
ex: `const NUMBER_IMAGES = 5;`

2023-10-11 07:22 UTC, Cardamced approved these changes

2023-10-11 07:39 UTC, YDrogen approved these changes

2023-10-11 07:40 UTC, merged