Feature/home header
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b pull request #8
Opened 2023-10-13 08:27 UTC by Mikazian

2023-10-13 08:54 UTC, Cardamced approved these changes

2023-10-13 10:09 UTC, Cardamced submitted a review, later dismissed

2023-10-13 12:43 UTC, YDrogen requested changes

2023-10-13 12:43 UTC, YDrogen commented on npx
Quel est ce fichier ? 🤔

2023-10-13 12:43 UTC, YDrogen commented on src/components/home/Home.jsx
> +  const randomIndex = Math.floor(Math.random() * GENRES_ID.length);
Va changer à chaque render ?
Peut être déplacé hors du component pour retirer ce comportement

2023-10-13 14:08 UTC, Cardamced submitted a review, later dismissed

2023-10-14 13:04 UTC, YDrogen requested changes

2023-10-14 13:04 UTC, YDrogen commented on .github/workflows/pr.yml
Il faudrait annuler ces changements

2023-10-14 13:04 UTC, YDrogen commented on src/components/home/Home.jsx
> +  };
Ces `const` ne nécessitent rien qui se trouve dans le component. Elles peuvent donc être sorties hors du component, au dessus

2023-10-15 07:50 UTC, herve-perel approved these changes

2023-10-15 08:14 UTC, herve-perel approved these changes

2023-10-15 13:33 UTC, YDrogen approved these changes

2023-10-15 13:33 UTC, merged